Repository NovatraX/exam-countdown-extension, pull requests merged in 2025-10, with the labels that each got.

#9 Implement GitHub Issue And Pull Request Templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/question.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: hacktoberfest, hacktoberfest-accepted

#11 feat: updated readme and contributing guide
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#21 feat: updated the homepage based on the given feedback
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#24 Fix exam day message not updating when changing exams
  src/newtab/newtab.js
Labels: bug, hacktoberfest, hacktoberfest-accepted

#27 Updated SECURITY.md
  SECURITY.md
Labels: hacktoberfest, hacktoberfest-accepted

#30 Add enhanced navbar with navigation links
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#35 feat(ui) : Add Back-To-Top Button with Smooth Scroll
  index.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#36 Allow users to set precise time of a custom exam & Set current time as min input time
  src/newtab/newtab.html
  src/newtab/newtab.js
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted

#42 feat : Add weather widget with custom location & auto detect
  manifest.json
  src/newtab/newtab.html
  src/newtab/newtab.js
  src/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
